# Generated by Django 5.0.6 on 2024-06-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
