# Generated by Django 5.0.2 on 2024-06-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.kanbanboard')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.task')),
            ],
        ),
    ]
