# Generated by Django 5.0.2 on 2024-07-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_timesheets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheets',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='timesheets',
            name='time',
        ),
        migrations.AddField(
            model_name='timesheets',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='status',
            field=models.CharField(choices=[('tobe_filled', 'To Be Filled'), ('submitted', 'Submitted'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='tobe_filled', max_length=20),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
