# Generated by Django 5.0.2 on 2024-07-04 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_remove_timesheets_task_list_remove_timesheets_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='status',
            field=models.CharField(choices=[('Tobe_submitted', 'To Be Submitted'), ('submitted', 'Submitted'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='Tobe_submitted', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timesheets',
            unique_together={('user', 'date')},
        ),
    ]
