# Generated by Django 5.0.2 on 2024-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_alter_timesheets_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetsubmission',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
